modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"


[[mods]]
modId = "${MOD_ID}"
version = "${MOD_VERSION}"
displayName = "${MOD_NAME}"
displayURL = "https://akazukin.org"
logoFile = "icon.png"
ordering = "NONE"
side = "BOTH"

authors = "Akazukin-Team"
description = '''${MOD_DESCRIPTION}'''


[[dependencies.${ MOD_ID }]]
modId = "neoforge"
type = "required"
versionRange = ">=20"
ordering = "NONE"
side = "BOTH"


# Here's another dependency
[[dependencies.${ MOD_ID }]]
modId = "minecraft"
type = "required"
versionRange = "=1.21.5"
ordering = "NONE"
side = "BOTH"
